[ssh]
tunnel_host = "YOUR_SSH_TUNNEL_HOST"    # e.g. "ec2-3-45-67-89.compute-1.amazonaws.com"
tunnel_port = 22
ssh_username = "ec2-username"
ssh_pkey = """
-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAr...
...(all the base64 lines exactly as in your .pem file)...
...==
-----END RSA PRIVATE KEY-----
"""

[postgres]
host     = "YOUR_PRIVATE_DB_HOST"       # e.g. "10.0.1.5" or internal DNS
port     = 5432
dbname   = "superset"
user     = "superset_user"
password = "YOUR_DB_PASSWORD"
